name: Simple Manual Workflow - Three Env

on: push


jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt large secret
        run: |
          echo "hello i am a prod"
        env:
          API_KEYS_PAGE_MOVIES: ${{ secrets.API_KEYS_PAGE_MOVIES }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/.env
